project_id = "rfrauluoyvichcjbzqlb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-product]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.ai-forecast]
verify_jwt = false

[functions.gdrive-import]
verify_jwt = false

[functions.gdrive-backup]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.visual-search]
verify_jwt = false
