  { icon: Receipt, label: 'POS หน้าร้าน', path: '/admin/pos' },
  { icon: ClipboardList, label: 'จัดการกะ', path: '/admin/pos/shift' },
  { icon: Receipt, label: 'บิล POS', path: '/admin/pos/transactions' },
  { icon: Package, label: 'Inventory Sync', path: '/admin/inventory' },
  { icon: Package, label: 'สินค้า', path: '/admin/products' },
  { icon: Upload, label: 'อัปโหลด AI', path: '/admin/upload' },
  { icon: ShoppingCart, label: 'คำสั่งซื้อ', path: '/admin/orders' },