  { icon: ClipboardList, label: 'จัดการกะ', path: '/admin/pos/shift' },
  { icon: Receipt, label: 'บิล POS', path: '/admin/pos/transactions' },
  { icon: Package, label: 'สินค้า', path: '/admin/products' },
  { icon: Cloud, label: 'Inventory Sync', path: '/admin/inventory-sync' },
  { icon: Upload, label: 'อัปโหลด AI', path: '/admin/upload' },
  { icon: ShoppingCart, label: 'คำสั่งซื้อ', path: '/admin/orders' },
  { icon: Users, label: 'ลูกค้า', path: '/admin/customers' },