import AdminBranches from './AdminBranches';
import AdminRecipes from './AdminRecipes';
import AdminUGC from './AdminUGC';
import AdminInventorySync from './AdminInventorySync';
import POS from './pos/POS';
import ShiftManager from './pos/ShiftManager';
import POSTransactions from './pos/POSTransactions';
    if (currentPath === '/admin/pos/shift') return <ShiftManager />;
    if (currentPath === '/admin/pos/transactions') return <POSTransactions />;
    if (currentPath === '/admin/products') return <AdminProducts />;
    if (currentPath === '/admin/inventory-sync') return <AdminInventorySync />;
    if (currentPath === '/admin/upload') return <AdminUpload />;
    if (currentPath === '/admin/orders') return <AdminOrders />;
    if (currentPath === '/admin/customers') return <AdminCustomers />;