import { AIForecastPanel } from '@/components/admin/AIForecastPanel';
import { RecentOrdersTable } from '@/components/admin/RecentOrdersTable';
import { LowStockAlert } from '@/components/admin/LowStockAlert';
import AdminInventory from './AdminInventory';
import AdminProducts from './AdminProducts';
import AdminOrders from './AdminOrders';
import AdminCustomers from './AdminCustomers';
    if (currentPath === '/admin/pos') return <POS />;
    if (currentPath === '/admin/pos/shift') return <ShiftManager />;
    if (currentPath === '/admin/pos/transactions') return <POSTransactions />;
    if (currentPath === '/admin/inventory') return <AdminInventory />;
    if (currentPath === '/admin/products') return <AdminProducts />;
    if (currentPath === '/admin/upload') return <AdminUpload />;
    if (currentPath === '/admin/orders') return <AdminOrders />;