import AdminBranches from './AdminBranches';
import AdminRecipes from './AdminRecipes';
import AdminUGC from './AdminUGC';
import AdminInventorySync from './AdminInventorySync';
import POS from './pos/POS';
import ShiftManager from './pos/ShiftManager';
import POSTransactions from './pos/POSTransactions';
    if (currentPath === '/admin/recipes') return <AdminRecipes />;
    if (currentPath === '/admin/ugc') return <AdminUGC />;
    if (currentPath === '/admin/settings') return <AdminSettings />;
    if (currentPath === '/admin/inventory-sync') return <AdminInventorySync />;
    return null;
  };
